### ISSUE TITLE
Could you offer the map file on npm?

### ISSUE THREAD

**Issue by kennynaoh** [720kb/highlighter.js#11]
Hello @45kb ,
I am the members of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
Could you add the `highlighter.min.js.map` on [npm](https://www.npmjs.com/package/highlighter.js)?
Because the `sourceMappingURL` you mention in [`highlighter.min.js`](https://github.com/kennynaoh/cdnjs/blob/cff215c28849d3b403df2f48949a0cc87e948646/ajax/libs/highlighter.js/0.1.8/highlighter.min.js#L12) has map file.
Please help me confirm that.
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8193
https://github.com/cdnjs/cdnjs/pull/8197

**Comment by 45kb** [comment]
Hi @kennynaoh  should be ok now with latest version https://github.com/720kb/highlighter.js/releases/tag/1.0.0

If any other problem let know, thank you.

**Comment by kennynaoh** [comment]
Looks great!
Thanks for your help
